apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: ko://github.com/izaakdale/kafka-client
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
